load(
    "//bazel:stackext_build_system.bzl",
    "stackext_catch_test",
)

stackext_catch_test(
    name = "linear_allocator_test",
    srcs = [
        "linear_allocator_test.cpp",
    ],
    deps = [
        "//:stackext_lib",
    ],
)
