cc_library(
    name = "unit_test",
    hdrs = [
        "unit_test.h",
    ],
    srcs = [
        "unit_test.cc",
    ],
    deps = [
        "@com_github_catchorg_catch2//:catch2",
        "@com_github_catchorg_catch2//:catch2_main",
    ],
    visibility = ["//visibility:public"],
)
