cc_binary(
    name = "quickstart",
    srcs = [
        "main.cc",
    ],
    deps = [
        "//bbai/memory/management:managed_ptr",
        "//bbai/memory/management:managed_ptr_utility",
    ],
)
